# Model Configuration
model:
  input_shape: [256, 256, 3]
  base_model: "Xception"
  fine_tune_at: 100
  num_classes: 5

# ArcFace Parameters
arcface:
  scale: 64.0
  margin: 0.50

# Training Parameters
training:
  batch_size: 16
  epochs: 100
  learning_rate: 0.00001
  early_stopping_patience: 20
  reduce_lr_patience: 5
  reduce_lr_factor: 0.2
  min_lr: 0.00001

# Data Parameters
data:
  train_dir: "multi-detector/train"
  validation_dir: "multi-detector/validation"
  test_dir: "multi-detector/test"
  target_size: [256, 256]

# Paths
paths:
  model_save_dir: "trained_models"
  model_name: "Xception_Multi_Detector.h5"